// Mocks generated by Mockito 5.4.6 from annotations
// in yumemi_flutter_github_repository_search/test/features/search/search_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:yumemi_flutter_github_repository_search/models/github_repository.dart'
    as _i2;
import 'package:yumemi_flutter_github_repository_search/services/api/github_api_client.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGitHubSearchResponse_0 extends _i1.SmartFake
    implements _i2.GitHubSearchResponse {
  _FakeGitHubSearchResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GitHubApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGitHubApiClient extends _i1.Mock implements _i3.GitHubApiClient {
  @override
  _i4.Future<_i2.GitHubSearchResponse> searchRepositories({
    required String? query,
    int? page = 1,
    int? perPage = 30,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRepositories,
          [],
          {
            #query: query,
            #page: page,
            #perPage: perPage,
          },
        ),
        returnValue: _i4.Future<_i2.GitHubSearchResponse>.value(
            _FakeGitHubSearchResponse_0(
          this,
          Invocation.method(
            #searchRepositories,
            [],
            {
              #query: query,
              #page: page,
              #perPage: perPage,
            },
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.GitHubSearchResponse>.value(
            _FakeGitHubSearchResponse_0(
          this,
          Invocation.method(
            #searchRepositories,
            [],
            {
              #query: query,
              #page: page,
              #perPage: perPage,
            },
          ),
        )),
      ) as _i4.Future<_i2.GitHubSearchResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
